### ISSUE TITLE
Lista urzędów skarbowych w oknie Nagłówek Formularza jest pusta

### ISSUE THREAD

**Issue by tomaszkoc** [PL-JPK/JPKEdytor#1]
Lista jest pusta, nie można zapisać danych nagłówka, wygenerowany plik XML jest niepoprawny.

![edytor_jpk_urzad](https://user-images.githubusercontent.com/10009621/34455689-99ded312-ed84-11e7-8daa-bafc06f70463.png)

Lista krajów w oknie Dane Podmiotu, też jest pusta

Błędy weryfikacji w wygenerowanym pliku XML znalezione przez program Klient JPK 2.0:
`V,0,Błąd wynikający z analizy dokumentu. org.xml.sax.SAXParseException; lineNumber: 11; columnNumber: 14; cvc-complex-type.2.4.b: The content of element 'Naglowek' is not complete. One of '{"http://jpk.mf.gov.pl/wzor/2016/10/26/10261/":KodUrzedu}' is expected.
V,1,Błąd wynikający z analizy dokumentu. org.xml.sax.SAXParseException; lineNumber: 19; columnNumber: 31; cvc-complex-type.2.4.a: Invalid content was found starting with element 'Wojewodztwo'. One of '{"http://jpk.mf.gov.pl/wzor/2016/10/26/10261/":KodKraju}' is expected.`

**Comment by jpk-edytor** [comment]
Poprawiłem [instalator](https://github.com/PL-JPK/JPKEdytor/releases/) - pliki .xsd powinny były trafić do podfolderu Schema.
