### ISSUE TITLE
Wysyłanie plików JPK

### ISSUE THREAD

**Issue by Lazys** [PL-JPK/JPKEdytor#2]
Hej, masz jakieś doświadczenie związane z implementacją w .Net wysyłania plików JPK do Ministerstwa Finansów?

**Comment by jpk-edytor** [comment]
Niestety nie... Nawet nie obejrzałem specyfikacji... Ale to chyba nic strasznego, najciekawsze pewnie będzie PInvoke dla biblioteki kryptograficznej do podpisania pliku.
